### ISSUE TITLE
Desired Features: Inactive Clients

### ISSUE THREAD

**Issue by Imagine3D-Ben** [RinsibleElk/Deadfile#13]
I don't want to delete a client when their job is done because they might come back but would it be possible if all the clients jobs are cancelled/completed that the client is then automatically inactive?

**Comment by RinsibleElk** [comment]
Yeah, easy enough. I will not do the same with jobs yet, however I can do
one day. The reason jobs require more thought is the more complex
relationships with a number of other entities.

**Comment by Imagine3D-Ben** [comment]
Perfect. I doubt I would want the same with jobs anyway because I want closing a job to be a manual thing that you are very conscious of, whereas losing a client happens as a direct result of their job(s) being closed. Basically it means you 'close' one item instead of two.
