### ISSUE TITLE
Job Children

### ISSUE THREAD

**Issue by Imagine3D-Ben** [RinsibleElk/Deadfile#16]
For the date issue we need the estimated decision date too. Also would it be possible for this also to have the active inactive states I mentioned...

Active = Undecided (or maybe Current is better?)
Inactive = Refused, Approved & Withdrawn

Applications frequently run past their decision date so being out of date isn't enough to make it inactive. 

Also can we add the view inactive checkbox to all of these job children? For Expenses and BillableHours this would obviously be paid and Applications would be any of the inactive states and JobTasks would be completed.

**Comment by RinsibleElk** [comment]
OK, something interesting about the billables among these, which makes me think we should review our decision about whether to separate the concepts of Application and ApplicationFee again.

The thought occurs that there are two separate things going on here, particularly with the state. One is measuring the state as regards how the Application is being processed (Current|Refused|Approved|Withdrawn). The other is measuring the state as regards payment (Unbilled|Billed|Paid|Cancelled). The latter would basically have its states updated by virtue of being included in an invoice, and then that invoice changing state. The former would have its states updated manually by you. What do you reckon?

**Comment by RinsibleElk** [comment]
Alternatively I just put two states on the application... one billable state, one application state. That probably works out easier and allows you to manage it as one entity - where the billable state need not apply.

**Comment by Imagine3D-Ben** [comment]
What if we just make the applications the same as tasks i.e. active or completed with no financial value whatsoever and just make an application fee an expense?

**Comment by RinsibleElk** [comment]
That might work well if you are happy to manage like that?

**Comment by Imagine3D-Ben** [comment]
Yep no problem. Maybe if we add an expense type combo box for expense type then this would be the better solution. Those things being...

Application fees
Professional fees
Title Deeds/Plans
Promap
Drainage Search
Other

As long as we keep a description box I don't see a problem with this.

**Comment by RinsibleElk** [comment]
These are in.
