### ISSUE TITLE
Billable Hours

### ISSUE THREAD

**Issue by Imagine3D-Ben** [RinsibleElk/Deadfile#20]
Could we add fields for who did the work and No of Hours for times when I don't know what the hourly rate would be

**Comment by RinsibleElk** [comment]
Do you want the Who bit to have any suggested values? I'm assuming you don't want me to try and guess the amount you'd charge given a number of hours? One option would be to allow hourly rates to be configured in some table - in this solution, I would provide a management page from the Home, which would just be:
Name | HourlyRate
-------+------------

And then the names would be suggestions in the Who box, and if you change the number of hours worked, it'll provide a suggested value for the billable. Useful?

**Comment by Imagine3D-Ben** [comment]
Well currently it would be me, Dad and Mike. Company (e.g. Ben on behalf of Imagine3D) would never happen. If Mike were to leave (especially given the current situation) we would need to add a new person if we got a replacement and for the foreseeable future it will only really ever be 2/3 people so for now I'll fill it out manually.

**Comment by Imagine3D-Ben** [comment]
Oh and no hourly rate that would be impossible to calculate. Dad makes it up each time.

**Comment by RinsibleElk** [comment]
This is kind of in there I think.
